### ISSUE TITLE
Custom Colours are not working in 1.0.77.338.g758ebd78

### ISSUE THREAD

**Issue by LambArchie** [khanhas/Spicetify#10]
Everything was working fine in the previous version but in this version it refuses to change. This is with my custom colour scheme and the default. From a quick look in the inspect element it looks like the names of some of the CSS elements have changed meaning not all colours applied. This is probably why the custom css is working but not the colours.

I also found I had to disable custom colour's before the custom css worked. Maybe that's related?

**Comment by khanhas** [comment]
Stay tune, I'm going to push a new update really soon. It has many new features so I need some time to test.

**Comment by khanhas** [comment]
I just updated Spicetify to version 1.5
Can you confirm that it works?
Remember to restore Spotify before updating new version.

**Comment by LambArchie** [comment]
Just tested and it is working. Thanks for the quick update. 
Can't see to find the lyrics button though, maybe its because I am not in the US (so unsupported region) or not a premium user. This is even with extremely popular songs.
Also can't see the Disable Sentry button, could also not spot it in the screenshot you provided.

EDIT: Just enabled the lyrics button and it says it is not available in my region https://i.imgur.com/Sgn2qlu.png

**Comment by khanhas** [comment]
Lyrics feature doesn't need premium. I didn't know that they restrict Lyrics feature in unsupported market.  I will push small fix soon.
Disable Sentry is a preprocess. It's only available when you're going to Backup

**Comment by LambArchie** [comment]
Just checked and it is. Thanks for your quick updates.

EDIT - Was referring to Disable Sentry not the Lyrics Feature

**Comment by khanhas** [comment]
Wait, lyrics works in your client again?
If it doesn't, I just updated Lua script and skin ini. Download repository zip file and extract to Spicetify skin folder.

**Comment by LambArchie** [comment]
Just checked and even though it enabled the icon and disables one of the error message it only takes me to the visualiser but no lyrics appear or it says no lyrics are available https://i.imgur.com/370EEWa.png

And no without this mod no option is available so it is definitely a region lock that is occurring.

**Comment by khanhas** [comment]
I need you to test something. Open the song Friends like in your screenshot.
Open up console in DevTool (hit Ctrl + Shift + i). Paste this in and see if it returns any response:
```
var trackId = chrome.playerData.track.uri.split(":")[2];
var lyricsUri = `hm://lyrics/v1/track/${trackId}`;
chrome.cosmosAPI.resolver.get(lyricsUri, (error,response)=>{
    console.log(JSON.parse(response._body))
})
```

**Comment by LambArchie** [comment]
Sorry I didn't reply earlier, here is the output
https://pastebin.com/z4MdMtc0
https://i.imgur.com/srTBBfG.png

**Comment by khanhas** [comment]
Oh no, there's something wrong with `response._body` or Spotify refuses to return lyrics request of unsupported region.
Last try:
Change `console.log(JSON.parse(response._body))` to `console.log(response)`
And just send me what is `response`, I don't need `RequestHandler`.

**Comment by LambArchie** [comment]
Sorry I took a while to respond https://pastebin.com/3XqHQgT5

**Comment by khanhas** [comment]
Reload the client, wait a bit till everything is loaded and try again

**Comment by LambArchie** [comment]
Figured out why the command wasn't working earlier, I disabled WebNowPlaying Companion because Cleartext was detecting both. For some reason this broke chrome.playerData. Anywhere here is the log https://pastebin.com/DvsHaUcL

**Comment by khanhas** [comment]
Alright, I'm sorry then. That request function is in lowest level to make everything in Lyrics app work. 
They actually refuse to return lyrics to unsupported region.
