### ISSUE TITLE
Discolored BG when moving displays

### ISSUE THREAD

**Issue by regret** [khanhas/Spicetify#11]
When moving Spotify to my 2nd monitor, a part of the client becomes discolored when skimming through different sections of the player.

Moving back to my main display doesn't replicate the issue whatsoever.

![screenshot_4](https://user-images.githubusercontent.com/34181576/38789056-a4f75196-4105-11e8-88c7-09e995015aeb.png)

![screenshot_5](https://user-images.githubusercontent.com/34181576/38789057-a50154ca-4105-11e8-844a-d998a5c3ef17.png)

**Comment by regret** [comment]
All of my background colors are identical, so i know it's not from the colors.


![screenshot_6](https://user-images.githubusercontent.com/34181576/38789074-c839da7a-4105-11e8-877f-c7f0a2cf6070.png)

**Comment by khanhas** [comment]
Can you record a video and upload to streamable.com ?

**Comment by regret** [comment]
Update, it's actually not a Spicetify issue!  

It turns out that there is a Hardware Acceleration option in Spotify Preferences under Advanced Options and this fixed the issue, I'm unsure as to why this would even cause that issue, but w/e I guess.

**Comment by khanhas** [comment]
I guess there's problem with your GPU card so it returns different color on different connection/monitor.  
At first, I thought you were using `f.lux` and it caused this color distortion.
