### ISSUE TITLE
Lyrics doesn't work. Hide Saved column in Songs collection.

### ISSUE THREAD

**Issue by dror-sullam** [khanhas/Spicetify#16]
1. The Lyrics Animation looks so good but the lyrics itself not working...
For example it writes "You caught us, we're still working on that one..."
I couldn't find a song with working lyrics
Is there a way to fix it?
how can I make it work?

2. Can you please change the X icon and the 3 dots icon to higher DPI icons?
After the latest UI update of Spotify these two icons are looking awful.

3. Is there a place where I can find extensions?
Because I realy need an extension that will make spotify
ask me twice before deleting a song from my library
if I ever click by mistake on the V icon of the song.

Anyway thank you for your work, spotify UI is looking beautiful now...

**Comment by khanhas** [comment]
1. It worked before but not now after update. Lyrics fetching function doesn't return anything.
2. Sorry I can't, they are native window element and nothing I can do about them. I guess you need to change Window scaling if they're blurry.
3. I don't think so. If you find any online, please do post them in https://spectrum.chat/spicetify.
How about hide that column? You can still remove song from library via right click menu.

Also, please change post Issue title to something more detail.

**Comment by dror-sullam** [comment]
"How about hide that column?"
Sounds great!
But what do you mean
Is there an option?
Or will you add this feature in the future?

Thanks anyway for the response! (:

**Comment by khanhas** [comment]
That would be easy. Don't need to make an extensions, click Edit CSS and add this in:
 ```css
div[data-play-source="library-collection"] .tl-save {
    display: none;
}
```
