### ISSUE TITLE
Where is the trashbin?

### ISSUE THREAD

**Issue by TheLongLife** [khanhas/Spicetify#17]
Hi. I've read about this trashbin feature but I can't seem to find it anywhere...Is the extension currently broken or am I just blind and can't see it?

**Comment by khanhas** [comment]
![image](https://user-images.githubusercontent.com/26436809/39407360-0c318e96-4bef-11e8-9535-ac3ddd2f1242.png)
![image](https://user-images.githubusercontent.com/26436809/39407363-1d466d1e-4bef-11e8-8e98-52b3e8bf790b.png)

**Comment by TheLongLife** [comment]
Ok, I'm not blind, I really don't have that icon, even though the trashbin extension is enabled.

**Comment by khanhas** [comment]
Can you reload/restart Spotify?

**Comment by TheLongLife** [comment]
Yes, I did that. Didn't help though.

**Comment by khanhas** [comment]
When you enabled Trashbin extension, did you hit Re-apply?

**Comment by TheLongLife** [comment]
Well it was checked from the getgo but I tried now to: disable trashbin extension, re-apply, restart and then I enabled it once again, re-apply and restart. That didn't work either.

**Comment by khanhas** [comment]
Ok, I need you to open `%appdata%\Spotify\Apps\zlink` folder.   
Check if `trashbin.js` file is in there.   
Also open index.html file and check if `<script type="text/javascript" src="/trashbin.js">` is in the last line.

**Comment by TheLongLife** [comment]
Yes, there is `trashbin.js` in `%appdata%\Spotify\Apps\zlink`
and Yes, `<script type="text/javascript" src="/trashbin.js">` is in the last line in index.html

**Comment by khanhas** [comment]
Ok, my mistake, I forgot that localStorage of TrashSongList and TrashArtistList could be null.
Click at Trashbin metadata zone in Spicetify skin, it will reveal an option for you to open Trashbin.js file. Replace entire that file with this: https://raw.githubusercontent.com/khanhas/Spicetify/master/Extensions/Trashbin.js
then save and Re-apply

**Comment by TheLongLife** [comment]
Works now! Thank you!
