### ISSUE TITLE
[Request] Queue-only party/DJ mode

### ISSUE THREAD

**Issue by Sparoney** [khanhas/Spicetify#18]
Hi, love this app!

I was wondering if it would be possible to make an extension so that whenever someone presses play on a song it adds it to the queue instead of playing it? This would allow people to set up their Spotify for use as a DJ or at a party! 

This will make it much easier than having to use a third-party site or program like Festify as they can limit Spotify's ability (using Musixmatch and Spotify Connect).

Thanks!
(I literally just signed up to GitHub so I could post this)

**Comment by khanhas** [comment]
Really cool idea! But it's not possible to change play functionality on other device, only yours. So if that's what you're looking for, read on.

All play track buttons only add that track to queue, not play directly.

I just uploaded a beta version, really need some test. I only managed to alternate Play button functionality, double click at track still plays it.

Now only button of tracks in playlist, search, artist page, album track list, radio episode list are available. 

Removing track from queue and Clear queue have to be done via Queue app.

Here link to extensions: https://github.com/khanhas/Spicetify/blob/master/Extensions/DJMode.js  

Click at Raw button and save file to `Documents\Rainmeter\Skins\Spicetify\Extensions`. Then load or refresh Spicetify skin in Manage Rainmeter, find and activate DJ Mode extensions and hit Re-apply.

**Comment by khanhas** [comment]
Toggle DJ Mode in Profile menu:  
  
![image](https://user-images.githubusercontent.com/26436809/39428846-16ad2776-4cb3-11e8-96c9-84e634d4a1bc.png)

**Comment by Sparoney** [comment]
Just tested it, works great! Would be cool if we could prevent the pause/play/skip/shuffle/repeat/volume/devices buttons from being clicked, so only the DJ can control that from another client via Spotify Connect. Possibly an alert like the blue Spotify alerts at the top to confirm the song was added?

Thanks!

**Comment by khanhas** [comment]
Added: https://github.com/khanhas/Spicetify/blob/master/Extensions/DJMode.js
Check it out

![image](https://user-images.githubusercontent.com/26436809/39467787-0607b2c2-4d5a-11e8-8bd7-2133814a09b3.png)

**Comment by Sparoney** [comment]
Works perfectly! Thank you!

**Comment by khanhas** [comment]
Thank you too, for this wonderful idea.

**Comment by Sparoney** [comment]
Would you be able to add in some visual queue so the user knows the song was added? If it's too much work don't worry about it, you've done more than enough!!

**Comment by khanhas** [comment]
Oh, I forgot about that haha. Let me see if I can leak toast function. It's cool enough to leak tho.

**Comment by khanhas** [comment]
Manually update `Document\Rainmeter\Spicetify\@Resources\Script.lua` with this: https://github.com/khanhas/Spicetify/blob/master/%40Resources/Script.lua.
Then update DJMode extension with previous link.
Refresh Spicetify skin and Re-Apply

![image](https://user-images.githubusercontent.com/26436809/39470470-25c61dca-4d68-11e8-9827-faf1607b6fd0.png)

**Comment by Sparoney** [comment]
Awesome work! This is amazing! Just a suggestion, I just changed `'is added to queue'` to `'added to queue'` so it sounds better. Thank you so much!
