### ISSUE TITLE
Spotify not working with Spicetify 1.5 or 1.6

### ISSUE THREAD

**Issue by mangogelato** [khanhas/Spicetify#20]
I got Spicetify when it was at 1.1 or 1.2, and i recently tried updating to 1.5 (and 1.6 as well) but found that it wouldn't work. There would be no errors on the app itself however recently when I try it stays stuck on 'Injecting a websocket and jquery 3.3.1'. My spotify stays blank, even if I uncheck all boxes. The menu in the top-left only displays File, Edit and View.

Restoring to backup makes my Spotify work again but without the Spicetify themes and I have tried deleting and re-installing both Spotify and Spicetify and installing Spotify from the @Resources page. Unchecking the 'Disable Sentry' and 'Disable UI logger' options didn't work either. Reverting back to my previous version works fine.

**Comment by khanhas** [comment]
Can you Open Log in Manage Rainmeter and see if there's any error.

**Comment by mangogelato** [comment]
![image](https://user-images.githubusercontent.com/38873298/39460815-cce6e32e-4d49-11e8-968f-5db822ed0bf7.png)

**Comment by khanhas** [comment]
Really sorry. I returned `App_ParseActivated` function before it could assign `length` fuction, that leads to this error.
Manually update `Document\Rainmeter\Spicetify\@Resources\Script.lua` file content with this:
https://raw.githubusercontent.com/khanhas/Spicetify/master/%40Resources/Script.lua

**Comment by mangogelato** [comment]
The error isn't showing up anymore but it's still not working

**Comment by khanhas** [comment]
Do you have Teamviewer?
Send me via https://spectrum.chat/users/khanhas

**Comment by Sparoney** [comment]
Spicetify 1.6.1 works perfectly fine on my Gaming PC running Windows 10 Home but has the same 'Injecting a websocket and jquery 3.3.1' error on my laptop running Windows 10 Pro. Unchecked every single option and the error is still there. 

This is the error: Rainmeter can't open 7z.exe or command prompt
![image](https://user-images.githubusercontent.com/38852913/39802552-b19f6082-53b1-11e8-84c1-c76311850d0e.png)

When running Rainmeter as admin however, the only error is this:
![image](https://user-images.githubusercontent.com/38852913/39802768-43e3f656-53b2-11e8-9873-e747f1397bdd.png)

**Comment by khanhas** [comment]
@NotSparon Does Spotify on your laptop have `%appdata%\Spotify\Apps` folder?
I suspect Windows has installed Spotify WIndows Store version for you and Spicetify can't find zlink app folder in `%appdata%\Spotify\Apps` to inject extension in.

**Comment by Sparoney** [comment]
@khanhas yes, my laptop does have the `%appdata%\Spotify\Apps` folder and `zlink.spa`. I have a different problem now as I've reinstalled Spotify multiple times and when it opens its just an 'invisible' transparent window. Don't worry about that though as I'll fix that myself. Still unsure why Spicetify won't work even though `%appdata%\Spotify\Apps` is there.

**Comment by khanhas** [comment]
Originally, Apps folder should contain bunch of spa files. After Spicetify is applied, they should be folders with same names. Can you check your client version?

**Comment by Sparoney** [comment]
Client is 1.0.77.338. The 'Error 103: Cannot start program' error is still showing up even when running as admin. Seems as though Rainmeter can't execute the files even though they are there. I've tried Rainmeter 4.1 and 4.2 beta.

**Comment by khanhas** [comment]
Please try 1.6.2 release and report back to me if it still doesn't work

**Comment by Sparoney** [comment]
Client version 1.0.80. Spicetify 1.6.2. `Error 103: Cannot start program` is still an error if I don't run as admin. It says 'Mod succeeded' but Spotify is still just a blank screen not loading.

**Comment by khanhas** [comment]
Send me teamviewer id via https://spectrum.chat/users/khanhas

**Comment by Sparoney** [comment]
I don't have Teamviewer and I don't want to install it because there was a big breach at Teamviewer a while ago.

**Comment by mangogelato** [comment]
I'm getting a new error with 1.6.2, I'm on 1.0.80.474.gef6b503e

![image](https://user-images.githubusercontent.com/38873298/39997000-a7d0a4aa-57c4-11e8-8581-ec9399a01e10.png)

**Comment by khanhas** [comment]
I just checked,  
`!UpdateMeterGroup` is valid bang  
All `UpdateMeterGroup` bangs I use have nothing wrong with them.
I don't know why Rainmeter throws that but is there any problem with your Spotify?

**Comment by mangogelato** [comment]
Haven't gotten the error again but the Spicetify still bricks my Spotify, now it won't let me move the window

**Comment by khanhas** [comment]
@channer72 @NotSparon Can you guys try version 1.6.3 and tell me if it works?

**Comment by mangogelato** [comment]
It's working! Thank you :)
