### ISSUE TITLE
Latest Release text centered when next to Artist's Pick

### ISSUE THREAD

**Issue by Sparoney** [khanhas/Spicetify#21]
![image](https://user-images.githubusercontent.com/38852913/39468361-f8a0e812-4d75-11e8-87b8-18c23a1e6bee.png)

After adding the CSS in issue #14 this still occurs when there is an "Artist's Pick" next to the latest release.

**Comment by khanhas** [comment]
![image](https://user-images.githubusercontent.com/26436809/39470583-b6024058-4d68-11e8-91e2-073893f916f9.png)
  
  
Weird, mine doesn't seem to have that issue. Did you save your user.css and hit Update CSS / Re-apply?

**Comment by Sparoney** [comment]
Yep, I just clicked Update CSS and Re-Apply, I even restarted and the issue is still there. Strange.

**Comment by khanhas** [comment]
Can you paste your user.css to github gist or pastebin, I will take a look.

**Comment by Sparoney** [comment]
https://gist.github.com/NotSparon/539b2a86bd5a6aed77850d64259755e3

**Comment by khanhas** [comment]
Ahaha! There are 2 CSS blocks control that element. They are all have `!important`  flag, and only last block is applied. In your case, the block you added is on top so it is overridden. 
Now just move it to the bottom of user.css.

**Comment by Sparoney** [comment]
Ah thanks, works now!
