### ISSUE TITLE
Spotify update 1.0.80.474 breaks DJ Mode

### ISSUE THREAD

**Issue by Sparoney** [khanhas/Spicetify#26]
I know this version isn't supported, but I updated to see what would still work. In 1.0.80.474 Christian mode shows up in the profile selector but DJ Mode doesn't. They must have changed part of their code. Just thought I'd let you know. I've downgraded back to 1.0.77.338 for the meantime. If you don't have the update in your region I can help debug.

**Comment by khanhas** [comment]
Fixed in [1.6.2](https://github.com/khanhas/Spicetify/releases/tag/1.6.2) release.
