### ISSUE TITLE
Queue All extension bug?

### ISSUE THREAD

**Issue by Sparoney** [khanhas/Spicetify#28]
Not sure if this is the Queue All extended functionality, but the Queue All button queues the 'More by Artist' songs instead of the album. Is it supposed to be up next to the play/save buttons and queue the album instead? In this case, the Queue All button adds the 'More by The Weeknd' songs.

![image](https://user-images.githubusercontent.com/38852913/39858290-72ecb0f6-5479-11e8-9928-cf0109674fae.png)

**Comment by khanhas** [comment]
Idea of Queue All buttons are helping user to play all items in Carousels, Album/EP list where adding each of them to queue is a huge chore and costing time.   
Albums and Playlists already have Play buttons or right click at ablum cover and select "Add to queue", I don't see why I should a Queue All button right there.

**Comment by Sparoney** [comment]
Ahh sorry, my bad! I completely forgot you could do that.
