### ISSUE TITLE
Lyrics not working

### ISSUE THREAD

**Issue by ghost** [khanhas/Spicetify#29]
I can't get lyrics working: when I click the buton there's just the animated background but no text, so I turned lyrics off and on again and again there's just animated background but now it says something like "Unfortunately there's no text for this song". But this text appears at every song :/

Spotify: 1.0.80.474
Spicetify: 1.6.2
related and enabled settings: Enable Lyrics, Lyrics button always show and I tried one time w/ Force no sync lyrics

**Comment by khanhas** [comment]
Sorry, Enable Lyrics feature worked before but doesn't after several updates. Seems like they restrict and refuse to return any lyrics in unsupported region at server side. And nothing I can do about that.

I should remove Lyrics feature in next release.
