### ISSUE TITLE
Possible Reddit App bug?

### ISSUE THREAD

**Issue by SladtheLad** [khanhas/Spicetify#30]
Love the new subreddit feature.

I don't know if this is a bug, but the playlist fetching didn't actually begin for me until I clicked on any of the header buttons a few times. On load, the lists were just blank. The "nothing to display" image wasn't even showing until I clicked around a couple times. Eventually, they all loaded fine.

**Comment by khanhas** [comment]
Thank you!
I fixed it in https://github.com/khanhas/Spicetify/commit/ecf5f3ba00e0a7c4d709ccd6dfb1595c6f1220ff
Please download bundle.js file and replace old one in `Spicetify\Apps\reddit` folder. 
Then hit Re-apply in Spicetify.

**Comment by khanhas** [comment]
Fixed in 1.6.3
