### ISSUE TITLE
Slider Disappearing

### ISSUE THREAD

**Issue by cubeslice** [khanhas/Spicetify#31]
Hello, I have a problem. I really enjoy using Spicetify, but there is a very annoying bug where the slider (music slider) disappears after reopening Spotify. If I reapply, it still does not appear, and the slider is invisible. The only way to get it back is to revert Spotify back to normal, then reapplying. Is there any way to fix this? Thank you.

**Comment by khanhas** [comment]
You mean Slider at bottom of the client?
![image](https://user-images.githubusercontent.com/26436809/40040297-e48a26e4-5843-11e8-9f74-3e53b042f569.png)

**Comment by cubeslice** [comment]
Yes, sorry for not providing a screenshot.

**Comment by khanhas** [comment]
I find no reason it should disappear.
What is your Spicetify setting?

**Comment by cubeslice** [comment]
I will send you screenshots when I get home.

**Comment by cubeslice** [comment]
![image](https://user-images.githubusercontent.com/35668016/40152857-0b93ac12-5955-11e8-8d2d-37be451750c1.png)

As you can see, the slider is not there despite the song playing. I did not change any of the settings at all, as I am too lazy haha.

**Comment by khanhas** [comment]
Oh no. I dont think it disappears though. Somehow replay button is misplaced and slider is pushed down.

**Comment by khanhas** [comment]
Top bar is also messed up. What version is your Spicetify? 
I think you have really old one. Try restore spotify and clear backup first, download latest Spicetify and then do the install routine again

**Comment by cubeslice** [comment]
okay, ill try that

**Comment by cubeslice** [comment]
Holy crap I just realized that my Spicetify version is incredibly old. I had to reset my OS a week ago, and the backup I used was from early March. Thank you.
