### ISSUE TITLE
Spotify 1.0.80 and Latest Spicetify not backup after first launch

### ISSUE THREAD

**Issue by Tr0NiX** [khanhas/Spicetify#32]
Hi my spotify client has updated to new version but skin cannot backup skin.. i tried reinstall rainmeter skin + rainmeter and i reinstalled spotify client 2 times with removing in %appdata% files .. but not working anymore ,, in log rainmeter says Error 103: Cannot start program: "C:\Windows\system32\cmd.exe" /U /C (Spicetify\Spicetify.ini - [Duplicate]) .. but i tried open rainmeter as admin but not working .. thanks for help have a nice day

**Comment by khanhas** [comment]
Wow, seems like you tried every possible solution I can suggest. 
Some users are still unable to use Spicetify, I tried to interact with their machine, tried all the step as you said but found no cause.  
So sorry, I don't think I can help you :(.

**Comment by Tr0NiX** [comment]
Maybe its problem only in version 1.0.81.325.g17f71170... bcause i have this installed..

**Comment by khanhas** [comment]
I just updated to version 1.6.3 with some fixes  
Please try it out and tell me if it works :) @Tr0NiX

**Comment by Tr0NiX** [comment]
Always showing this error  https://imgur.com/a/uATrN4V i will try install on fresh system (virtual machine) and i post result .. but on windows 10 machine works fine .. idk why on windows 7 not working ..

**Comment by khanhas** [comment]
Ok, maybe problem lies in robocopy command and flags I am using.
Open command prompt and type this in:
```
robocopy /? >> robocopy.txt
```
This will export all `robocopy` available flags in Win7 to `robocopy.txt`.
Send me that file here.

**Comment by Tr0NiX** [comment]
https://www92.zippyshare.com/v/9EjPRuhQ/file.html

**Comment by khanhas** [comment]
Hmm.  
You run that command on Win7 right?   
I expect one or some invalid flags but it actually has everything I used.

**Comment by Tr0NiX** [comment]
yes on windows 7 x64 enterprise .. or can u disable backup ? i will backup manually folder

**Comment by Tr0NiX** [comment]
Its working on VM .. i only copy this folder and replace in my main pc .. Thanks for help :)

**Comment by khanhas** [comment]
What is VM's Win7 edition? Is it Enterprise?  
Since you have everything you need in main PC, can you try this to see what is wrong with `robocopy`:
Open command prompt with normal privilege:
```
cd %userprofile%\Documents\Rainmeter\Skins\Spicetify\@Resources\Extracted
robocopy "Raw" "Test" *.css *.js *.html /S /COPY:D /R:50 /W:1 /NJH /NS
```

**Comment by tr0nix123** [comment]
VM is virtual machine ... alright i will try and i post result.. thanks :)

**Comment by khanhas** [comment]
Haha, I mean what edition of win7 did you install on your VM?

**Comment by khanhas** [comment]
Oops, I missed `@Resources\Extracted`
Correct commands should be:
```
cd %userprofile%\Documents\Rainmeter\Skins\Spicetify\@Resources\Extracted
robocopy "Raw" "Test" *.css *.js *.html /S /COPY:D /R:50 /W:1 /NJH /NS
```

**Comment by tr0nix123** [comment]
i installed on vm same edition . Enterprise X64

**Comment by Tr0NiX** [comment]
cd %userprofile%\Documents\Rainmeter\Skins\Spicetify\@Resources\Extracted
causing in cmd : The system cannot find the path specified (i replaced %userprofile% ) and i tried open cmd with admin priv.

**Comment by Tr0NiX** [comment]
I think i have problem with cmd commands https://imgur.com/a/Dg4xIvb

**Comment by Tr0NiX** [comment]
THANKS Its working fine .. (over rmskin) have a nice day :)

**Comment by Tr0NiX** [comment]
however injecting extensions not working .. https://imgur.com/a/FuunOcE

**Comment by khanhas** [comment]
Huh, your win7 doesn't have `robocopy`. 
This version: https://github.com/khanhas/Spicetify/releases/tag/1.6.5  should rule out your injecting bug.

**Comment by Tr0NiX** [comment]
https://imgur.com/a/dnJWERk

**Comment by khanhas** [comment]
Sign out and sign in again I think
Also remember to restore Spotify and clear backup before installing new Spicetify version

**Comment by Tr0NiX** [comment]
now works fine .. i updated spotify cleared backup and apply new theme . working fine .. :)
