### ISSUE TITLE
Can't start DJ mode

### ISSUE THREAD

**Issue by rafalrojek** [khanhas/Spicetify#33]
I want to use DJ mode on my spotify but I can't found a option on my Spotify. All Extensions are enabled

![image](https://user-images.githubusercontent.com/16052286/40530753-49571f88-5ffa-11e8-98f3-28f17e0bc2e6.png)

**Comment by khanhas** [comment]
Can you let me know what is your Spotify version and Spicetify version?
Also make sure your Spicetify is on latest first.

**Comment by rafalrojek** [comment]
So, I want check my Spicefi version and I don't see anything. I donload last version from web and installed. After that I see the information that I must reinstall Spotify. After reinstall and new pathing everything works properly. Thanks :D
