### ISSUE TITLE
Black screen after applying skin

### ISSUE THREAD

**Issue by Teck1325** [khanhas/Spicetify#36]
As the title says. After I apply the skin Spotify restarts on a black screen. 

Spotify version: 1.0.80.474.gef6b503e
Spicetify version: Spicetify_1.6.2

**Comment by khanhas** [comment]
Please try this:
1. Clear backup in Spicetify
2. Uninstall Spotify, install it again with installer, and make sure its version is 1.0.80.474.gef6b503e
3. Backup and apply Spicetify again

**Comment by Teck1325** [comment]
Still get a black screen.

**Comment by khanhas** [comment]
Can you Open Log in Rainmeter Manage and see if Spicetify throws any error

**Comment by khanhas** [comment]
Can you Open Log in Rainmeter Manage and see if Spicetify throws any error

**Comment by Teck1325** [comment]
Oh yeah now that you mention it.. it seems like it can't open 7z.exe.

**Comment by khanhas** [comment]
Ok. now restore spotify first  
Try this version and tell me if it works
https://drive.google.com/file/d/1nlYiaG3dBM8mhaM61D6JhCpoJrKA1qUD/view?usp=sharing

**Comment by Teck1325** [comment]
Doesn't work either.

**Comment by khanhas** [comment]
Ouch.
We need to go deeper i think.
Open `%appdata%\Spotify\prefs` with anything but Notepad.
Add or change this line:
```
app.enable-developer-mode=true
```
Restart Spotify, hit Ctrl Shift i, switch to Console and see if it throws any error

**Comment by Teck1325** [comment]
The console is empty on stock and themed Spotify.  Also thanks for the help so far!

**Comment by khanhas** [comment]
It's ok :)  
But I have to sorry, seem like we tried everything.
Also this is a known issue to me, I still don't know what could cause this on only some machines.

**Comment by Teck1325** [comment]
Man, I was so hyped when I saw this tool.. On Linux theming with oomox is no problem. It's always something with windows. Anyways thanks for your work again and have a nice day o/.

**Comment by khanhas** [comment]
Wait a minute, any chance your Rainmeter\Skins folder are on OneDrive, because there was someone mentioning me before about it. Windows won't let you run any exe from OneDrive.
If it isn't, try run Rainmeter as Administrator.

**Comment by Teck1325** [comment]
Cant be OneDrive because I purged it of my system. Running rainmeter as administrator didn't solve it either. I still think it has something to do with the 7z.exe. Every time I hit apply it says in the logs that it cannot be launched.

**Comment by Teck1325** [comment]
Error 103: Cannot start program: C:\Users\USER_HERE\Documents\Rainmeter\Skins\Spicetify\@Resources\7z.exe (Spicetify\Spicetify.ini - [Unzip])

**Comment by khanhas** [comment]
Can you run 7z.exe via command prompt to see if there is any problem with it

**Comment by khanhas** [comment]
Actually `Error 103` is belong to parameter/flag, not program itself.  
I just updated to version 1.6.3 with small fix in Unzip command, please try it out and tell me if it works.
@Teck1325

**Comment by Teck1325** [comment]
Sorry for answering so late. I just tested the new version and everything works just fine! No more problems.
