### ISSUE TITLE
Songs not leaving where I last left off

### ISSUE THREAD

**Issue by cubeslice** [khanhas/Spicetify#40]
This issue is kind of hard to explain so bear with me. Before I installed this, whenever I'd close Spotify and open it again, it would be ready to play the song that I was playing before I closed it. Now, for some reason, it doesn't remember what song I was playing. I would be listening for a whole hour, close the app, and when I would open it again, it does not remember any of the songs I just played. Sorry, this issue is hard to explain, but do you have a fix? I do have premium, but before I had premium, I did not get any ads. Does this have something to do with it? Thank you.

**Comment by khanhas** [comment]
Hmm, it should remembers last song you play before closing it, it works correctly in mine.   
Can you try Restore -> Clear backup -> close Spotify completely,  then backup and apply again?

**Comment by cubeslice** [comment]
Thank you. It worked. I've done this multiple times before trying to fix this. I don't think I closed Spotify completely before. Thank you.
