### ISSUE TITLE
Small personal fixes :)

### ISSUE THREAD

**Issue by porrige51122** [khanhas/Spicetify#43]
This is continued from the conversation on spectrum:
https://spectrum.chat/thread/79987017-d7f0-4a4d-a2f6-e4907b93e6e5
You seem to be more active on here:

The opacity on hover is working great, But is there a way you can make it click through the album art rather than go to the song.

Next, I think you got confused when I asked about the left sidebar. The width of the sidebar I have changed already because I wanted it wider. the problem was is when using the small cover big cover mechanism. When the picture is locked (it shows the picture when the sidebar hover is activated) with the sidebar, it is the wrong size. The picture is the one I wanted to resize, not the sidebar.

Thanks so much for this. All the additions you have made for spotify look great!

**Comment by khanhas** [comment]
1. I don't think there is an easy way to do that. You can disable click interaction of the cover by following these steps:
 - Open Extensions folder by click at the link at bottom of skin UI.
 - Create a new JS file.
 - Add this line in:
```js
$(".cover-image-container .cover-image").prop('onclick',null).off('click');
```
 - Save that file
 - Refresh Spicetify skin UI in right click menu
 - Find your just created extension in Extension section, activate it and Re-apply.

Sadly, I don't know how to make it click-through.

2. Open your user.css, change `width` and `height` of these elements:
```css
#view-now-playing.expanded
```
```css
#now-playing-image-large .cover-image
```
