### ISSUE TITLE
Not remembering the last song that was played (again!)

### ISSUE THREAD

**Issue by cubeslice** [khanhas/Spicetify#44]
Hello. A few weeks ago I had a problem where Spotify would not remember what song I was last playing. I thought it was fixed, but it really wasn't, but I felt bad about bothering you again. Spotify only remembers what song was last played if I exited out of the app a few seconds after starting a new song. Hour-long sessions would not be remembered whatsoever if you look in the history. I have done many backups and restores. Are there any fixes?

**Comment by khanhas** [comment]
Sorry to hear about that.
It never happens to me in any version. It only forgets what I was playing when I force close it with Task Manager or AHK. If I close it with Spotify tray menu icon or shut computer down, it remembers correctly.

I did try to make a extension to store last listening session and set it in next start up. But it's not stable enough and cause more trouble than being helpful.

**Comment by cubeslice** [comment]
Yeah, it just might be my computer. Oh well. Thanks for the help though.
