### ISSUE TITLE
Artist/Album page with no CSS at all.

### ISSUE THREAD

**Issue by nodgear** [khanhas/Spicetify#45]
Playlists work's great, and appear howit should be, but if you click in a artist/album everything goes crzy
![image](https://user-images.githubusercontent.com/22383863/42175448-d1b21d3c-7dfb-11e8-85fc-0a1b220e0e8a.png)

**Comment by khanhas** [comment]
1. Restore
2. Make sure you are on lastest Spicetify.
3. Clear backup
4. Backup and Apply again.

**Comment by nodgear** [comment]
I just download spotify and spicetify 2 hours ago.
did the backup steps, still the same.
![image](https://user-images.githubusercontent.com/22383863/42177129-fba981ce-7e01-11e8-95a9-9f7294462949.png)

**Comment by khanhas** [comment]
What is your Spotify version?
Check in Menu in top left -> About

**Comment by nodgear** [comment]
Spotify 1.0.84

**Comment by khanhas** [comment]
Can you zip folder `artist` in `%appdata%\Spotify\Apps` and send it here?

**Comment by nodgear** [comment]
[artist.zip](https://github.com/khanhas/Spicetify/files/2156276/artist.zip)
Here you go.

**Comment by khanhas** [comment]
Seems like your artist's index.html is modded 2 times.
Correctly modded index.html should looks like this:
```html
<!DOCTYPE html>
<html dir="auto">
  <head>
    <meta charset="utf-8">
    <meta name="google" value="notranslate">
    <link rel="stylesheet" href="https://zlink.app.spotify.com/css/glue.css">
    <title>Artist</title>
  <link href="/css/main.css" rel="stylesheet"><link rel="stylesheet" class="spicetify-userCSS" href="https://zlink.app.spotify.com/css/user.css"></head>

  <body>

    <div id="artist-page" data-play-source="artist"></div>
    <div id="message-container"></div>

    <!-- "init.js" is served by the desktop client and provides the "window.__spotify" object. -->
    <script src="init.js"></script>
  <script type="text/javascript" src="/artist.bundle.js"></script></body>
</html>
```

Can you clear backup, reinstall Spotify again then backup and apply again. 
If you can, uninstall Spotify first just to be sure.

**Comment by nodgear** [comment]
Working like magic, any clue about how this bug happens?

**Comment by khanhas** [comment]
Tbh, I can't think of any.  
Backup, extracted and processed files need to be deleted before user can backup and process them again. If somehow it isn't deleted, it will still be overwritten by original file when extracting.
