### ISSUE TITLE
Two problems with Spotify

### ISSUE THREAD

**Issue by Ein6tein** [khanhas/Spicetify#52]
Downloaded zip of this repo, inzipped and dropped into \My Documents\Rainmeter\Skins folder.

Two issues that I have are:

1. Whenever I try to apply theme it gets stuck on "Leaking useful functions and objects"
2. WebPlayingNow of monstercat visualizer doesn't interact with WebPlayingNow of Spotify, yet works perfectly fine with Chrome's (for Youtube)

**Comment by khanhas** [comment]
1. Can you Open Logs in Rainmeter Manage and see if it throws any error?
2. WebNowplaying Websocket port in Spicetify is the same as WebNowplaying in browser, but only one is able to connect at a time. But would be later, let's debug the first problem first.

**Comment by Ein6tein** [comment]
Okay,

After I made backup, it showed this error:

> Plugin: Unable to load "MessagePassing" (error 126) (Spicetify-master\Spicetify.ini - [WebSocket])

And on Apply it showed next errors:

> Cannot inject extensionspicetifyWrapper.js. Check %appdata%\Spotify\Apps\zlink folder to see if it exists.
> Cannot inject extensionjquery-3.3.1.min.js. Check %appdata%\Spotify\Apps\zlink folder to see if it exists.
> Script: Script.lua:880: attempt to index local 'f' (a nil value)

**Comment by khanhas** [comment]
Can you check that folder as error said

**Comment by Ein6tein** [comment]
zlink - it's not a folder, but a file with ".spa" extension

**Comment by khanhas** [comment]
Ok, exit Spotify completely.
Hit Clean Backup in skin UI, Backup again. Then see if you can apply

**Comment by Ein6tein** [comment]
Same stuff.

As far as I understood - it either requires file extension when it addresses zlink, or I miss folder.
And I think it's first case.

**Comment by khanhas** [comment]
No, it supposes to copy extracted zlink package (along with other packages) to `%appdata%\Spotify\Apps` when you hit Apply. There shouldn't be any spa package in that folder also.
I don't know what's wrong with copying process. But try these:
1. Exit Rainmeter and run it again as Administrator. Clean Backup and try again to see if your machine actually restrict you from editing file in `%appdata%` folder.

2. If it still doesn't work:
- Manually delete all Spa packages in `%appdata%\Spotify\Apps`.
- Copy all folder in `Documents\Rainmeter\Skins\Spicetify\@Resources\Extracted\Raw` into `%appdata%\Spotify\Apps` first.

![image](https://user-images.githubusercontent.com/26436809/43254434-91570dde-90f1-11e8-9680-76d93d19a4c0.png)

![image](https://user-images.githubusercontent.com/26436809/43254062-b1bc6656-90f0-11e8-87f6-d9a3369fba66.png)

- If you wish to change UI colors, copy all folder `Documents\Rainmeter\Skins\Spicetify\@Resources\Extracted\Themed` into `%appdata%\Spotify\Apps` also. 

- Refresh Spicetify skin in right click menu or Rainmeter Manage:

![image](https://user-images.githubusercontent.com/26436809/43254127-e34ed154-90f0-11e8-8ddb-a90028ac2e7c.png)

- And hit Re-Apply button

**Comment by Ein6tein** [comment]
1. Didn't get any notifications or errors about not being able to edit files in %appdata%
2. ... I don't have "Extracted" folder in @Resources

**Comment by khanhas** [comment]
Oh wow it doesn't even extract Spa files. Do you have Backup folder in `Spicetify\@Resources` folder that contains bunch of spa files?

**Comment by Ein6tein** [comment]
Yes, and whenever I Clear backup they disappear

**Comment by khanhas** [comment]
I guess last option is remove your Spicetify then installing it again with rmskin package in release page.
https://github.com/khanhas/Spicetify/releases/download/1.7.3/Spicetify_1.7.3.rmskin

I doubt it will changes anything but I'm out of idea. It supposes to extract to Extracted folder.

**Comment by Ein6tein** [comment]
Unfortunately re-installing it with rmskin didn't help :(

Oh well...

What about WebNowPlaying - is it possible to use Chrome and Spotify?

**Comment by khanhas** [comment]
You haven't been able to inject anything in so it won't work. 
What is your Windows version?

**Comment by Ein6tein** [comment]
Win 10 Pro

**Comment by khanhas** [comment]
Ok, I tried to make another version with Powershell to extract spa file but it doesn't work at all. So I think I still have to use 7zip. 
Can you help me debugging what is wrong with it?
First, hit Backup. Based on your situation, I  guess it would just copy all spa file to `Backup` folder without extracting anything to `Extracted` folder.
Open cmd and type in these commands: 
```bash
cd "%userprofile%\Documents\Rainmeter\Skins\Spicetify\@Resources"
```
```bash
7z.exe x "Backup\about.spa" -oExtracted\about\ -r
```
And screenshot or copy and paste output here.

**Comment by Ein6tein** [comment]
Looks like my problem is that My Documents folder is kept on remote storage. Here's error from cmd:
> CMD does not support UNC paths as current directories

**Comment by khanhas** [comment]
I don't know then. I never deal with "remote storage" before or know how to use one.
