### ISSUE TITLE
Elapsed and Remaining Text

### ISSUE THREAD

**Issue by Inertialus** [khanhas/Spicetify#54]
Is there any way to return the elapsed and remaining text whilst keeping the progress bar spanning across the bottom of the window? I'm not sure why but moving the text closer to the center of the client in the css shortens the progress bar.

**Comment by khanhas** [comment]
Use DevTool, Inspect Elements in Spotify to find class or id of element
Hit Edit CSS to open user.css file and put your custom stylesheet in.
Hit Update CSS or Re-apply when you're done.
