### ISSUE TITLE
Shuffle+ non-functional

### ISSUE THREAD

**Issue by Aria-NL** [khanhas/Spicetify#55]
Installed Spicetify today, in high hopes of a better Shuffle feature. When attempting to use Shuffle+, the buttons are there but do nothing when pressed. There's no feedback saying "x songs shuffled" nor does the actual play queue reorder itself. Any ideas?
![2018-07-27_09-23-43](https://user-images.githubusercontent.com/14789279/43323177-dba5d72a-917e-11e8-94d9-ff930d541e4e.gif)

**Comment by Amber26Theta** [comment]
https://i.imgur.com/XRvBk3k.gifv

**Comment by khanhas** [comment]
It's still working in mine https://imgur.com/TDMvGcl
Can you activate Developer Mode in Spicetify skin (client should be restarted after but if it doesn't please close it completely and open again)
Hit Ctrl + Shift + i to open Console, type in
```js
Spicetify.test()
```
to see it has any error.

Then try to click Shuffle buttons in Queue page and see if it throws any error also.
Capture screenshot or copy paste here

**Comment by Aria-NL** [comment]
I enabled the dev mode and suddenly the shuffle buttons work. Very weird.

**Comment by khanhas** [comment]
Fixed it in 1.7.4
No need to enable Developer mode to use it now
