### ISSUE TITLE
All of my tabs on the left side are gone now.

### ISSUE THREAD

**Issue by anastasia-v-r** [khanhas/Spicetify#56]
Issue: My spotify has lost all of the left side tabs and the ui elements for clicking on my profile are also gone, its not a simple drop list that has none of the boxing and such.

Rain meter ver: 4.2.0 r3111 64bit
Windows: Windows 10 1803
Spicetify: 1.7.4

![image](https://user-images.githubusercontent.com/24751378/43368478-a2f1df74-932b-11e8-90c4-769df695e772.png)

**Comment by anastasia-v-r** [comment]
Another issue with the Css, The progress bar is so low and cutoff that i can barely grab hold of it to change song progress

**Comment by khanhas** [comment]
This is my custom theme, it behaves as I want. If it somehow doesn't fit your needs or too inconvenient, uncheck **Inject CSS** or hit **Edit CSS** button to open `user.css` file and clear it.
Then hit **Re-apply** button.

**Comment by anastasia-v-r** [comment]
okay thank you, Please do specify that to other @khanhas because its not clear that the auto applied starter theme/css will nuke your sidebar. Thanks for spicetify tho! it solved my problem with my visualizer and no more local api. <3

**Comment by khanhas** [comment]
Haha, it doesn't nuke sidebar.  
Sidebars are hidden but they can be expanded by hover on the right or left edge of spotify windows. 
I made them that way since my monitor is not every big and I don't use them all the time.
