### ISSUE TITLE
Luv Spicetify, but a few questions...

### ISSUE THREAD

**Issue by DlfnAntx** [khanhas/Spicetify#59]
Hello, 
Since I'm new to your Rainmeter add-on and GitHub, I apologize if I missed some obvious detail,
but I cant change the size of the sidebars, as they keep popping open and closed when I click to expand their size. (maybe even an option to have permanent sidebars, kinda annoying with 2 screens)
Another thing,
I'm modifying another Rainmeter add-on and would like to be able to get the current album picture and % through song by coding the add-on to reference your add-on for the data. I'm not entirely sure how to reference it, but if I can, I think it would be pretty kewl.
Thanks!
P.S.
Awesome job on Spicetify, it's looking great!

**Comment by khanhas** [comment]
1. https://github.com/khanhas/Spicetify#custom-css 's note
2. You mean "Rainmeter skin". Can you post its INI file here?

**Comment by DlfnAntx** [comment]
Thanks for the help, here's the .ini
[fill-player.zip](https://github.com/khanhas/Spicetify/files/2258703/fill-player.zip)

**Comment by khanhas** [comment]
[fill-player.zip](https://github.com/khanhas/Spicetify/files/2258707/fill-player.zip)

Make sure you have "WebNowPlaying" plugin and `WebNowPlaying Companion` extension injected in Spicetify.

If you haven't had WebNowPlaying plugin:  
1. Download rmskin package in https://github.com/tjhrulz/WebNowPlaying/releases
2. Install only plugin

**Comment by DlfnAntx** [comment]
Have the Plugin but the companion isn't injected there, the file you sent, for probably that reason, doesn't display any info, with now a loss of controls.
could you maybe send a download for the companion?
also, the .ini I'm modifying is from the Lim!t skin, if that helps

**Comment by DolfinGamer** [comment]
Wait...
I actually don't have the companion, can u send a download?

**Comment by DlfnAntx** [comment]
Here's a list of my current extentions:
autoSkipExplicit
Autoskipvideo
DJMode
QueueAll
Shuffle+
Trashbin
wnpPlugin

**Comment by DlfnAntx** [comment]
OOF
IM AN IDIOT
u already put it in the skin
my apologies

**Comment by DlfnAntx** [comment]
._.

**Comment by DlfnAntx** [comment]
but it still doesn't work
even with the companion

**Comment by khanhas** [comment]
1. Activate WebNowPlaying Companion in Spicetify
![image](https://user-images.githubusercontent.com/26436809/43672328-e7458334-97d5-11e8-8144-a07cf9b461c2.png)
2. Hit *Re-Apply* button
3. Restart Spotify, restart Rainmeter

**Comment by DlfnAntx** [comment]
well thanks for the help!
also ya I saw that after I posted
ugg that was pretty dumb
: )
