### ISSUE TITLE
"Browse" text disappearing, as well as other titles.

### ISSUE THREAD

**Issue by yPedx** [khanhas/Spicetify#6]
Basically the title says it all. Because of this the search bar also lands on 2 colors, making it ugly. I'll provide some screenshots to illustrate what I mean.
How it normally is after startup.
![image](https://user-images.githubusercontent.com/26491360/36068323-f1c3f322-0ed2-11e8-9853-2c6d3a6f7562.png)

How it is right when I launch Spotify, before it disappears and changes into the pic above.
![image](https://user-images.githubusercontent.com/26491360/36068335-5adc4d14-0ed3-11e8-9a6e-82cb350d83c0.png)

**Comment by khanhas** [comment]
It's not suppose to work like that. I recommend you to Restore, Clear backup, Backup again and Apply.  
This is how it looks in mine: https://streamable.com/zm62u  

If nothing is changed, remove `padding-top: 20px !important;` of class `.zlink-app-header ` in user.css
  
![image](https://user-images.githubusercontent.com/26436809/36071187-e3f4a07e-0f3c-11e8-994c-76b04441cd9b.png)

**Comment by yPedx** [comment]
Seems like it happens even with the normal Spotify client. I guess it's my problem then.

**Comment by yPedx** [comment]
Solved.
For those who may have the same problem, turn off "Show announcements about new releases" in your preferences.
