### ISSUE TITLE
Spicetify doesn't work.

### ISSUE THREAD

**Issue by synically** [khanhas/Spicetify#60]
I honestly don't know why; it genuinely is making me feel like a fucking retard (more than I diagnostically am)

I install spotify (web version, not microsoft)
I installed the latest Spicetify version
I open spicetify (Spotify  wasn't open)
I click backup
I customize what I want, I click apply. My spotify doesn't change. I'm frustrated & lost, if anything I honestly feel like I need a picture fucking tutorial.

**Comment by Altirix** [comment]
ive already injected my css and JS but i can just about remember it

1) backup
2) enable inject CSS and replace colours
3) enable live update
4) apply
5) Update CSS? shouldn't need to but incase skipping this fails.
5.1) restart

shitty lightshot if that helps http://prntscr.com/kge5np
