### ISSUE TITLE
Album artwork doesn't load up

### ISSUE THREAD

**Issue by ProtoBoyGG** [khanhas/Spicetify#62]
Spotify Artwork on any page(Homepage, playlists)etc. or even on now playing bar 
doesn't load up for a majority of albums only for a very few of them

How to fix this?

**Comment by ProtoBoyGG** [comment]
![screenshot 7](https://user-images.githubusercontent.com/28356342/44272553-cfb06380-a25a-11e8-949a-c994a938c526.png)
![screenshot 8](https://user-images.githubusercontent.com/28356342/44272554-d048fa00-a25a-11e8-89fe-bbf094b33d83.png)

**Comment by ProtoBoyGG** [comment]
![screenshot 9](https://user-images.githubusercontent.com/28356342/44273137-397d3d00-a25c-11e8-90af-fbf7c261d63e.png)

**Comment by khanhas** [comment]
Can you hit Restore -> Clear Backup then try again?

**Comment by ProtoBoyGG** [comment]
ok trying

**Comment by ProtoBoyGG** [comment]
did it still no luck

**Comment by ProtoBoyGG** [comment]
should I uncheck live update o[ption if that helps?

**Comment by khanhas** [comment]
What is your Spotify version?

**Comment by ProtoBoyGG** [comment]
![screenshot 10](https://user-images.githubusercontent.com/28356342/44276165-53228280-a264-11e8-8b9c-0bbd1182a277.png)

latest after what you told me to do

**Comment by ProtoBoyGG** [comment]
how to check that?

**Comment by ProtoBoyGG** [comment]
![screenshot 11](https://user-images.githubusercontent.com/28356342/44276241-882ed500-a264-11e8-9cc7-c0a266088998.png)

**Comment by khanhas** [comment]
Check Developer Mode in Spicetify
Restart Spotify client
Hit `Ctrl Shift i` to open cosole in Spotify client.
Screenshot me the console

**Comment by ProtoBoyGG** [comment]
wait

**Comment by ProtoBoyGG** [comment]
![screenshot 12](https://user-images.githubusercontent.com/28356342/44276449-11dea280-a265-11e8-94a4-48b4d30603d6.png)

**Comment by ProtoBoyGG** [comment]
how to fix this?

**Comment by khanhas** [comment]
Click at **Console**
