### ISSUE TITLE
Christian Mode/DJ Mode Toggles not available.

### ISSUE THREAD

**Issue by DiNitride** [khanhas/Spicetify#63]
Spicetify Version: 1.7.4
Rainmeter Version: 4.2.0
Spotify Version: 1.0.88.353.g15c26ea1 (Non-Windows Store)

Despite both extensions being loaded, neither options appear in the profile menu.

Steps taken so far:
- Restarting Spotify and Rainmeter
- Disabling injecting CSS and not replacing colours to check the menu wasn't being overridden.

I have attached images to show the issue. If you have any other troubleshooting ideas/fixed, or require any additional information, let me know.

Cheers :)

![image](https://user-images.githubusercontent.com/17622831/44569418-30b3cc00-a772-11e8-862e-9a21d0acd977.png)
![image](https://user-images.githubusercontent.com/17622831/44569430-3ad5ca80-a772-11e8-962f-90aac7858027.png)

**Comment by khanhas** [comment]
Fixed in 1.7.5
Thank you!

**Comment by DiNitride** [comment]
Thanks for quick fix and response! :D
