### ISSUE TITLE
Some Spotify elements dont change color

### ISSUE THREAD

**Issue by pavvelb** [khanhas/Spicetify#65]
Hello @khanhas ! Thank you for your work, you make a nice Rainmeter plugin, finally possible change colors of Spotify!
Im choose colors for white theme of Spotify, but it have elements what wont coloring, It is the header on home screen, in search results, and album page (if entering from spotify catalogue)
Can you please, make possibility change color of this header in Spicetify setting!) Really want white Spotify theme! 
![2018-08-30](https://user-images.githubusercontent.com/39178626/44875646-7b1fd600-aca7-11e8-9f6c-157a38595861.png)
![2018-08-30 1](https://user-images.githubusercontent.com/39178626/44875667-8a9f1f00-aca7-11e8-893c-0d06b48ea1a6.png)
![2018-08-30 2](https://user-images.githubusercontent.com/39178626/44875673-8e32a600-aca7-11e8-9352-48fbe85f8b3e.png)

**Comment by khanhas** [comment]
Thank for your feedback!
Main purpose of Spicetify is providing an easy way to customize and apply theme. I can't keep track of every element style in every new update.
If one of elements is out of place:
- Enable Developer Mode and check Inject CSS in Spicetify
- Hit Ctrl + Shift + i and use Inspect Element find element's class or id
- Open user.css by hitting Edit CSS button in Spicetify
- Add element's style to user.css 
- Hit Update CSS button to update and reload client.

**Comment by pavvelb** [comment]
Actually I don’t understand nothing in coding and CSS)

So, I’m inspect element and add in the end of user.css next

}

.Header__content-wrapper container {
    background-color: white;/* -webkit-mask-image: linear-gradient(transparent 48px, black 72px); */;

}

Im add background color and disable texture or image. Im save css? reload
And nothing changes

**Comment by khanhas** [comment]
Did you hit Update CSS or Re-apply?

**Comment by khanhas** [comment]
Fixed in 1.7.6
