### ISSUE TITLE
After a Spotify update...

### ISSUE THREAD

**Issue by CircuitRCAY** [khanhas/Spicetify#66]
...the borders of the and some of the UI have been removed in the SpicetifyDefault theme as seen below.

What it was: https://camo.githubusercontent.com/80b4b751dffd2392ecb321e2f0e864a781b4a21f/68747470733a2f2f692e696d6775722e636f6d2f6569415046366a2e706e67

What it is: https://circuit-is.theworstme.me/2a1ec0.png

**Comment by khanhas** [comment]
1. There is no new Spotify update in my client.
2. As its look, I guess you unchecked Inject CSS in Spicetify.
Check it and hit Re-apply button

**Comment by khanhas** [comment]
Check out version 1.7.6! I made various fixes.
