### ISSUE TITLE
Rounded Corners and Headers seem broken

### ISSUE THREAD

**Issue by HarvardYard** [khanhas/Spicetify#67]
I don't recall having an update to Spotify Client, however, in Recently Played and Home the header gradients from the client seem to have returned. Also, I have noticed that the rounded corners are broken for the Home screen. I have looked through the user.css file and also Spotify's dev console and haven't had much luck (I don't understand much about CSS) however I did notice I can't find the class "glue-page-header" within the Development Console. I also noticed that when adjusting colors it doesn't work every time. I am going to do a fresh install of Spotify and see what happens. I'll post what I find here.

**Comment by HarvardYard** [comment]
Fresh install and same problems. Inject CSS and Replace Colors is on. Not sure what's causing the rounded corners. Just wanted to let you know. And thank you for designing this awesome piece of tech. I am very appreciative of all the work you do to keep this thing working.

**Comment by khanhas** [comment]
Fixed in 1.7.6
