### ISSUE TITLE
Crashing Rainmeter?

### ISSUE THREAD

**Issue by MerrittJ** [khanhas/Spicetify#68]
Hi,

I downloaded Spicetify and found I need to update my Rainmeter from 4.0 to 4.2. I do so and my skins work as expected, but when I install the Spicetify skin (using SkinInstaller.exe, is there another way?), my Rainmeter crashes on startup until I remove the Spicetify skin folder. 
Have I done something wrong?

**Comment by khanhas** [comment]
Open `Documents\Rainmeter\Skins\Spicetify\Spicetify.ini` and  
try this: https://github.com/khanhas/Spicetify/blob/master/Spicetify.ini#L40

If you remove that section, you need to reload/restart Spotify client yourself after Applying.

**Comment by euaaron** [comment]
Hi, i couldn't mute the thread. May u stop sending me these notifications?
________________________________
De: khanhas <notifications@github.com>
Enviado: quarta-feira, 3 de outubro de 2018 06:34
Para: khanhas/Spicetify
Cc: Subscribed
Assunto: Re: [khanhas/Spicetify] Crashing Rainmeter? (#68)


Closed #68<https://github.com/khanhas/Spicetify/issues/68>.

**Comment by khanhas** [comment]
@euaaron Lol, un-watch the repo
