### ISSUE TITLE
Song Time Progress bar

### ISSUE THREAD

**Issue by NeliBrown** [khanhas/Spicetify#69]
less of a problem and more of a suggestion (unless its only for me) but the song progress bar (in the default css theme) doesn't have a number so if I want to jump for a specific point in the song I got no clue where it is.

plus the bar is at the complete bottom which makes it sometimes hard to hit while in windows mode since its kinda small and on the complete edge of what's clickable.

if there's a way/guide to fix those that would make the default css theme perfect.

**Comment by khanhas** [comment]
If my default theme causes more problem for you, it's best to uncheck **Inject CSS** then **Re-Apply** to use Spotify original UI  .   
If you know how to use Devtool, Inspect element and some CSS knowledge, you can try modifying my theme or making your own.
