### ISSUE TITLE
Feature Idea: Minimize Right Side Bar

### ISSUE THREAD

**Issue by Exper1mental** [khanhas/Spicetify#7]
Hi khanhas.

First of all, I just wanted to say that I absolutely love Spicetify! I've been looking for something like this for some time. I love the minimize feature for the left sidebar and thought it would be really cool if this feature was also implemented for the right sidebar.

Best Regards,
Exper1mental

**Comment by khanhas** [comment]
Thank you. I really appreciate it.  
The feature you suggest is also what I really want.
I did try to finding for right sidebar class name but I failed. I honestly don't know or deduce what it is from Spotify CSS, then I decided not to waste more time on it.
I leave this Issue open until you or anyone find out its class name or any element relating to it, I will pick up from there.

**Comment by OllieMH** [comment]
Spotify lets you do this in the settings, in display options, uncheck "Show right sidebar"

**Comment by khanhas** [comment]
@OllieMH That's not what we want. We want it to behave like left sidebar: hover on window's edge to expand it.

**Comment by khanhas** [comment]
Available in v1.3. Try it out.
