### ISSUE TITLE
UI Window Too Large

### ISSUE THREAD

**Issue by DistilledMeat** [khanhas/Spicetify#70]
Is there any resize option for the UI? My screen size is 1366x768 and this is what I'm seeing:
![toolarge](https://user-images.githubusercontent.com/20403072/45049305-cd4e6600-b0b0-11e8-81ef-b8aa7155a348.JPG)

**Comment by khanhas** [comment]
Adding scale would be huge work for me with this complex UI. So I think you need to drag and move it a bit to the left to access Apps section.

Uncheck `Keep on screen` in Rainmeter Manage
Also set skin position to `On Desktop` so it doesn't overlap your windows.

![image](https://user-images.githubusercontent.com/26436809/45073176-68265f00-b108-11e8-9c79-8b19acdc112d.png)

**Comment by DistilledMeat** [comment]
Well, I'm hoping for a resize option hidden or if I can change values in a variable that will change the whole UI but this is ok atleast now I can drag the UI. Besides, there is nothing hidden on the part where I can't see before. Thanks very much. Very awesome rainmeter skin!
