### ISSUE TITLE
Suggestion/request?

### ISSUE THREAD

**Issue by ghost** [khanhas/Spicetify#71]
Hello! Just want to start off to thank you for this amazing work, really hated Spotify's current design and this makes everything so enjoyable.

One thing that I've noticed with a lighter theme is that not everything is changable.
Wondering if it's possible to fix this, it only shows on albums, not playlists.

https://i.imgur.com/iMk2xB8.png
![](https://i.imgur.com/iMk2xB8.png)

Cheers!

**Comment by khanhas** [comment]
It's expected. I can't make them magically change and fit every single color scheme, at least one or 2 things stand out. That's when custom CSS come in handy. But it requires you to know CSS syntax and rules.
Enable Developer mode in Spicetify. Open up user.css by click at Edit CSS.
Restart Spotify, hit `Ctrl Shift i` to fire up DevTools and use Inspect Element to find button element. Try changing color in right side panel. When you feel ok with it, copy the css rule to your user.css.

Also, update your Spotify client, it's old
