### ISSUE TITLE
feature request: playback time/song duration

### ISSUE THREAD

**Issue by prsho** [khanhas/Spicetify#72]
it'd be nice to have an extension/option to get the playback time of the song back from the original spotify client. even something crude like this would be nice as an extension:
![image](https://user-images.githubusercontent.com/12502953/45899909-2eae4e80-bdac-11e8-859a-32b152e56883.png)

**Comment by khanhas** [comment]
`user.css` is yours to change.   
1. Hit Edit CSS button in Spicetify to open up `user.css`
2. Enable Developer Mode to be able to use Inspect Element and DevTool to find element class name.
3. Adds CSS rules for them in `user.css`
4. Hit Update CSS and reload Spotify.
