### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by mbs0ft** [khanhas/Spicetify#73]
![image](https://user-images.githubusercontent.com/22106304/46039281-98608c80-c10d-11e8-9e3d-6a59d578cfbf.png)
![image](https://user-images.githubusercontent.com/22106304/46039774-dad69900-c10e-11e8-9ac1-9ed61b7149d5.png)
![image](https://user-images.githubusercontent.com/22106304/46039790-e1fda700-c10e-11e8-8dc7-299bb6719e63.png)
![image](https://user-images.githubusercontent.com/22106304/46039799-e9bd4b80-c10e-11e8-8c34-abaeeb256595.png)
![image](https://user-images.githubusercontent.com/22106304/46039815-f772d100-c10e-11e8-8dc9-65f1f393c962.png)

**Comment by khanhas** [comment]
Please Clear Backup in Spicetify
Reinstall Spotify and try again
