### ISSUE TITLE
Shuffle+ Can't Shuffle Playlist Folder

### ISSUE THREAD

**Issue by Godlikehobbit** [khanhas/Spicetify#74]
If a user plays a playlist folder and attempts to use the "Shuffle Context" button, it returns "Unsupported context URI type: folder".

Shuffle queue still works though

**Comment by khanhas** [comment]
Hmm, they must add folder URI type recently. I will take a look later see if  I can get tracks list from it.

**Comment by Godlikehobbit** [comment]
Having a play around with their API, it appears to not return an external_url when you're playing from a folder.

Spotify also appear to acknowledge the issue and refuse to implement it according to spotify/web-api#38

**Comment by khanhas** [comment]
Not really.
If you can access a page which lists all tracks in that folder, or at least all playlists in that folder, I think I can make it work.
I won't be able to use my PC next 2 days so hang on.

**Comment by Godlikehobbit** [comment]
As far as I can tell, clicking on the folder just shows a list of all the playlists in said folder, closest thing to that would be the queue that is formed when you play a folder. The only way I can think of would be to use that as a way to get each playlist in the folder then use the API to get all the songs in those folders and sort that. I'm just not sure how to get that list of playlists from the history page where the shuffle button appears.

**Comment by Godlikehobbit** [comment]
I'll see what I can do while you don't have access to your PC

**Comment by khanhas** [comment]
Try this and tell me if it works ok: 
https://github.com/khanhas/Spicetify/blob/Shuffle%2B-folderShuffle/Extensions/Shuffle%2B.js

**Comment by Godlikehobbit** [comment]
Works brilliantly as far as I can tell, well done!

**Comment by khanhas** [comment]
Added in v1.7.7
