### ISSUE TITLE
Incorrect navigation highlighting

### ISSUE THREAD

**Issue by jackcml** [khanhas/Spicetify#75]
In the "Browse" tab, when you click on Charts, the Overview tab is highlighted instead. If you click it again, it will display correctly. ![navigation](https://user-images.githubusercontent.com/41037937/46265825-3c747a00-c4f8-11e8-81f2-02779c9b0724.gif)

**Comment by khanhas** [comment]
I think it's Spotify client bug itself, not because of Spicetify. If you Restore and try it in vanilla Spotify, bug is still there.  
Weird thing that it only occurs in Podcasts and Chart tabs, other tabs still behaves correctly.
