### ISSUE TITLE
Navigation 

### ISSUE THREAD

**Issue by sonic123tin** [khanhas/Spicetify#76]
Its kinda hard trying to access your friends list on the right and the playlists on the left, at a certain minimized window size you cant hover to see your friends list. Also it's feels weird needing to get your cursor really close to the edge of the window to open the side panels. Please consider to make an option to have the side bars open at all times, it feels more natural and easier to access to me this way, also make it easier to access these side bars for those who want to keep this feature of hovering over to access the side panels. Thank You for taking your time to read this!

![image](https://user-images.githubusercontent.com/43870546/46515529-52ed3f00-c832-11e8-884e-6885d5b51832.png)
( Cursor is invisible. ) ( In this image above you can see my friends list wont open. )

![image](https://user-images.githubusercontent.com/43870546/46515549-757f5800-c832-11e8-9381-6b7c14e3022b.png)
( Cursor is invisible. ) ( In this image my cursor was able to open the playlists. )

**Comment by khanhas** [comment]
Again.
You can uncheck Inject CSS to revert to original Spotify UI.
Or you can edit `user.css` (by hittting `Edit CSS` button in Spicetify) and remove my custom sidebar CSS rules.
