### ISSUE TITLE
Backup problem

### ISSUE THREAD

**Issue by NighterNyx** [khanhas/Spicetify#78]
I press backup but nothing happend, It's say preparing CSS files and that it.
I wait for about 10 minutes and it's still saying preparing CSS files.

**Comment by NighterNyx** [comment]
I tried restart my computer but it's not work either.

**Comment by khanhas** [comment]
Make sure you're using normal Spotify, not Windows Store Spotify

**Comment by NighterNyx** [comment]
Thanks it's work! I didn't know that have to be normal spotify.

**Comment by NighterNyx** [comment]
Anyways do you know how to make sidebar always show? like friends activity.

**Comment by NighterNyx** [comment]
Nevermind. I just have to make new theme to make it always show.
