### ISSUE TITLE
Backup not working. 

### ISSUE THREAD

**Issue by ScriptedThunder** [khanhas/Spicetify#79]
Everytime I click backup it says "Preparing CSS Files" and then goes back to "Please backup first". 

Gif of me clicking backup https://i.imgur.com/xgEJRdj.gifv
What it says in Rainmeter logs https://i.imgur.com/V01elqT.png

**Comment by khanhas** [comment]
https://github.com/khanhas/Spicetify/issues/78

**Comment by ScriptedThunder** [comment]
I am using the Normal Spotify.

**Comment by khanhas** [comment]
1. Uninstall SPotify completely
2. Go to folder `C:\Program Files\WindowsApps` and delete any folder has Spotify in its name.
3. Install Spotify, Clear Backup in spicetify if you can and Backup again

**Comment by ScriptedThunder** [comment]
I uninstalled Spotify then searched my entire C: drive and removed anything with the name of Spotify in it. I still have the error. https://i.imgur.com/b7vkLB0.png

**Comment by khanhas** [comment]
Are you using OneDrive or Dropbox to storage your Documents\Rainmeter folder?
If so, move to your local drive because exe can't be launched if it's in cloud folder.

**Comment by ScriptedThunder** [comment]
No. But I moved it to my desktop and I still am getting same error.

**Comment by khanhas** [comment]
`robocopy` isn't available because system32 path isn't added in environment path
Adding `C:\Windows\System32` to Path should make it work.
