### ISSUE TITLE
Spotify new UI

### ISSUE THREAD

**Issue by Meti0X7CB** [khanhas/Spicetify#8]
Spotify new UI doesn't work with Spicetify anymore

**Comment by khanhas** [comment]
You need to clear backup and backup again before you apply.
If you've already applied, reinstall Spotify and do as I said above

**Comment by NBSDEVApp** [comment]
I have do this on fresh install but doesnt work ?!

**Comment by Exper1mental** [comment]
I cleared the backup, made another backup, and applied again. Spicetify doesn't change anything now.

**Comment by khanhas** [comment]
Reinstall Spotify, update to new version in About page and try Spicetify v1.3.

**Comment by armanckeser** [comment]
![screenshot 45](https://user-images.githubusercontent.com/15313331/37014896-a50acd4c-20d1-11e8-8b37-aec5fb0a3deb.png)
I have no idea why, but my spotify looks like this. How can I fix it? Thanks.

**Comment by khanhas** [comment]
@armanckeser Hover on the left to expand sidebar then click at button in cover image to change to smaller size.

**Comment by armanckeser** [comment]
Thank you

**Comment by Jhonmark24** [comment]
Please spotify transparent glass option ,please.
