### ISSUE TITLE
[DJ Mode] Album page play button issue

### ISSUE THREAD

**Issue by Sparoney** [khanhas/Spicetify#80]
Hi,

With DJ Mode, Hide Controls works perfectly, except it hides the play (now queue) button on album/song pages, making it useless. Playlists and artist pages are unaffected and work fine. 

Would you be able to fix this?

Thanks,
Sparon

**Comment by Sparoney** [comment]
@khanhas any updates on this? Desperately need this fixed asap!! Thanks 👍

**Comment by khanhas** [comment]
https://github.com/khanhas/Spicetify/commit/df554c73eb0c049f094e49444ee2d22359d01fe0
