### ISSUE TITLE
Spotify or Spicetify broken?

### ISSUE THREAD

**Issue by Vision919** [khanhas/Spicetify#82]
<img width="401" alt="meow djduddudue" src="https://user-images.githubusercontent.com/44306917/47267525-06348400-d513-11e8-8913-7705ec3acf6a.PNG"> It says something is wrong, and I tried reinstalling it 5 times. Please help. Ty

**Comment by khanhas** [comment]
Can you uninstall Spotify first, delete Spotify in `%appdata%` then install again?

**Comment by Vision919** [comment]
I'll see if that works, BTW my spotify installs in: C:\Users\MyName\AppData\Local\Microsoft\WindowsApps\Spotify.exe. So I have to do ALOT of stuff to make sure spicetify knows where spotify is b/c usually spotify installs in appdata/roaming, but not for me.  So i'll just delete spotify in where MY spotify is.

**Comment by Vision919** [comment]
Also just a quick question, do i need developer mode enabled to backup? Also a suggestion you should make it so you can show spicetify where your spotify is.

**Comment by Strazdonis** [comment]
Are you using the store version of Spotify? If so download it from the website

**Comment by khanhas** [comment]
No, you don't have to enable Developer mode.
And only one valid spotify path is `%appdata%\Spotify`. If your spotify is in any other folder (like `WindowsApps`, they're unwrittenable and I can't make it to work.

**Comment by Vision919** [comment]
> Are you using the store version of Spotify? If so download it from the website

yes. I'll try using the website. Ty

**Comment by Vision919** [comment]
> No, you don't have to enable Developer mode.
> And only one valid spotify path is `%appdata%\Spotify`. If your spotify is in any other folder (like `WindowsApps`, they're unwrittenable and I can't make it to work.

Ok. Thanks

**Comment by mendel3** [comment]
My spicetify isn't injecting. It was working a couple of days ago, and isnt working now. It is the website version and in the correct folder.

**Comment by khanhas** [comment]
@mendel3 Clear Backup -> reinstall Spotify -> Backup and try again

**Comment by Vision919** [comment]
New info: When downloading the website version it is installing to the rigth folder until it just says "migrating data" and all the files are moved to the /windwsapps  and now it turned into the microsoft version.

**Comment by khanhas** [comment]
@Vision919 Uninstall Spotify
In your WindowsApp folder and `C:\Program Files\WindowsApps`, find any folder has "Spotify" in its name and delete that folder.
Install normally with installer, it shouldn't install Windows Store version now.

**Comment by mendel3** [comment]
Will this keep on happening?

**Comment by khanhas** [comment]
When Spotify updates new version, you need to remember follow instruction in skin that tell you to Clear Backup of old version and backup new one. 
That's all

**Comment by Vision919** [comment]
Try all of that thanks.
