### ISSUE TITLE
Can't backup, skin refreshes itself almost right away.

### ISSUE THREAD

**Issue by Emil4691** [khanhas/Spicetify#87]
![rainmeter_2018-12-06_16-02-21](https://user-images.githubusercontent.com/41549530/49592122-99653400-f970-11e8-8372-5a4b7f42178f.jpg)

**Comment by khanhas** [comment]
1. Open cmd
2. Run 
```bash
robocopy
```
and screenshot me output

**Comment by Emil4691** [comment]
![cmd_2018-12-06_17-16-19](https://user-images.githubusercontent.com/41549530/49596474-af77f200-f97a-11e8-87a7-fc8b52273b63.jpg)

**Comment by Emil4691** [comment]
Thanks for your help, adding C:\Windows\System32 to Path fixed the issue of robocopy not being recognized, and after closing Rainmeter from Task Manager and opening it again backing up works perfectly. Amazing rainmeter skin you've made, really great work!

**Comment by khanhas** [comment]
Oh ok. Good job on figuring it out.

**Comment by Emil4691** [comment]
Thank you.
