### ISSUE TITLE
Fonts not changing with new Spotify version

### ISSUE THREAD

**Issue by kaifengw** [khanhas/Spicetify#88]
Ever since updating Spotify (late November ish), the fonts in the interface don't change from the default. Everything else seems to be working though

**Comment by khanhas** [comment]
What did you do to change font?

**Comment by kaifengw** [comment]
I've been using a copy of reddit user bonecharm's user.css which I found online - here's the snippet of the code I think is supposed to change the font
```
/*  
Original Theme: Thicktify by 8roly (https://sta.sh/01uc5a80m46u)
Edited Theme: Moon Child by bonecharm (https://www.reddit.com/user/bonecharm)
Moon Child V1.0
Last Updated: September 3 2018
*/
html {
	font-family: "Karla"!important; /* Change font here */
}
h1 {
	font-family: "Karla"!important; /* Change font here */
	/*text-transform: uppercase!important;*/
	font-weight: bold;
}
```

**Comment by khanhas** [comment]
Do this instead:
```css
body {
	--glue-font-family: Karla;
}
```
You can remove those font-family rules in other elements

**Comment by kaifengw** [comment]
Thank you, that did it for me. I also had to remove any other instance where I tried to define font-family; they seemed to cause conflict issues with the system font.
