### ISSUE TITLE
Player Buttons 

### ISSUE THREAD

**Issue by Crazyshakespeare** [khanhas/Spicetify#89]
I have noticed the control buttons at the bottom of the player no longer work....I can play and pause from the playlist but the bottom most controls no longer work for me. Also is there any way to hide the ads like in the older releases?

**Comment by khanhas** [comment]
They still work normally in mine.
Did you change CSS? If so, send me yours.
And sorry, no, I can't help you hide/block ads.

**Comment by Crazyshakespeare** [comment]
Thank for the quick reply...attached is the code......I apologize that the code is so messy, I have a friend working on it as well so its not very clean! Thanks for the help.

https://gist.github.com/Crazyshakespeare/6b4f11e760c357b636abb503bb969249

**Comment by khanhas** [comment]
Use gist:
https://gist.github.com/

**Comment by Crazyshakespeare** [comment]
Thanks for directing me to gist....above is the link...Thanks again!

**Comment by khanhas** [comment]
Are you sure you copied CSS correctly?  
Wrong syntax all over the place. Comment missing `*`, rules block missing closing bracket `}`,...

**Comment by Crazyshakespeare** [comment]
Yes, that's the CSS...like I said I had a friend helping with it so its gotten a little messy. The biggest issue is in full screen the buttons don't seem to work but if I shrink the window down, say in half they seem to be working then. What would cause this?

**Comment by khanhas** [comment]
I can't help you debug until you fix all syntax error, they're just too much

**Comment by ghost** [comment]
i don't have the issues this person is describing. I suggest reinstalling spotify and re-downloading the latest version of spicetify as a troubleshooting step.

**Comment by khanhas** [comment]
Actually he needed help on his custom CSS but somehow it was messed up too much and I can't use it.
Since he abandoned, I close this Issue.

**Comment by ghost** [comment]
@khanhas Oh my bad.
