### ISSUE TITLE
UI Broken Spicetify

### ISSUE THREAD

**Issue by ghost** [khanhas/Spicetify#91]
UI seems to be broken; can't check boxes. Clicking them still works though.

![Broken UI](https://i.gyazo.com/962749d141c32a6f9ea7e9163d2ad7fd.png)

**Comment by khanhas** [comment]
Can you Restore Spotify (if already applied) then reinstall Spicetify? Icon font I included in skin package might be corrupted.

**Comment by ghost** [comment]
Didn't make a difference. If I try to install the fonts to my system Windows rejects them as an invalid font files.

**Comment by khanhas** [comment]
[Fonts.zip](https://github.com/khanhas/Spicetify/files/2750995/Fonts.zip)

**Comment by ghost** [comment]
The arrows on the right side of the skin are now rendering but the check boxes on the left still don't

**Comment by khanhas** [comment]
I don't know anymore. It works normally on mine, maybe your Windows has font problem, 
If you have some time, check out https://github.com/khanhas/spicetify-cli. It's command-line tool, customize with config file. So you don't need to deal with font or Rainmeter.

**Comment by ghost** [comment]
Just needed to restart machine... weird. All the font awesome things seem to be working now.
