### ISSUE TITLE
Can't Backup Spotify

### ISSUE THREAD

**Issue by gerald-lbn** [khanhas/Spicetify#92]
![capture](https://user-images.githubusercontent.com/36128190/51073113-8418af00-166c-11e9-834d-45d24e4d4e25.PNG)

**Comment by khanhas** [comment]
Add `C:\Windows\System32` to Environment variable `PATH`
Restart Rainmeter

**Comment by gerald-lbn** [comment]
I already have this on the PATH
C:\Users\Responsable\AppData\Local\Programs\Python\Python37-32\Scripts\

**Comment by khanhas** [comment]
You need to add  C:\Windows\System32 in PATH

**Comment by gerald-lbn** [comment]
I've done this but still the same error
![image](https://user-images.githubusercontent.com/36128190/51075510-9276c300-168c-11e9-83ef-c1dfe0ab7192.png)

**Comment by khanhas** [comment]
Can you restart your PC, just to make sure Environment Variable is updated correctly.
Restarting Rainmeter usually is enough.

**Comment by gerald-lbn** [comment]
I have restarted my pc but it doesn't work

**Comment by khanhas** [comment]
In Environment Variable window, do you have this variable:
![image](https://user-images.githubusercontent.com/26436809/51086566-d0eaab80-177a-11e9-8bac-9c8d050b18be.png)

If not, please add it with `New...` button
`ComSpec`  `C:\Windows\system32\cmd.exe`

**Comment by gerald-lbn** [comment]
Ok thanks now it's working i think i misclock and delete this path.
Now you can close this issue.
Thanks again
