### ISSUE TITLE
Full Screen Visualizer

### ISSUE THREAD

**Issue by Rubeanie** [khanhas/Spicetify#94]
Sorry to post it here but I didn't know where to put it, but I was wondering if you could make a plugin or a piece of CSS code, but I was wondering if you could make a way to have a visualizer on Spotify when you put it in full-screen mode.
thanks.

**Comment by aaryan45** [comment]
Please make it!

**Comment by khanhas** [comment]
Sorry I don't think I can make it. Building a unique page like that is beyond my knowledge.
My Reddit page was purely modified from Spotify's default pages
