### ISSUE TITLE
Use default spotify design with spicetify features

### ISSUE THREAD

**Issue by Bluscream** [khanhas/Spicetify#95]
I want to keep the default design with only some minor (non-color) changes but still have all the other features of Spicetify. How would I do that?

I already tried copying a empty version of "SpicetifyDefault" to "Themes" but that results in a completely pink Spotify window :(

![image](https://user-images.githubusercontent.com/3318223/53039192-e7bda580-347e-11e9-9c7a-9fba2c58e424.png)

**Comment by khanhas** [comment]
Uncheck Inject CSS and Replace Colors
Then Re-apply

**Comment by Bluscream** [comment]
Worked, thanks :)
